"""
PyTorch LoRA fine-tune script for the Prompt Injection Detector environment.

Loads failure cases from dynamic_attacks.json and the agent's episode logs,
formats them as an instruction-tuning dataset, and runs LoRA fine-tuning on
a small Llama model using PyTorch + PEFT + TRL.

Usage:
  python scripts/finetune.py
  python scripts/finetune.py --task pipeline --epochs 3 --output evals/finetune_results.md

Requires: pip install torch transformers peft trl bitsandbytes accelerate
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from typing import Any, Dict, List

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(REPO_ROOT, "server", "data")
EVALS_DIR = os.path.join(REPO_ROOT, "evals")

SYSTEM_PROMPT = (
    "You are an expert AI security analyst specializing in prompt injection detection. "
    "Analyze the message or tool output for prompt injection attacks and respond with valid JSON."
)

TASK_INSTRUCTION = {
    "easy": "Analyze this message for prompt injection attacks.",
    "medium": "Analyze this message carefully — the injection may be subtle or buried.",
    "hard": "Analyze this multi-turn conversation for social engineering injection patterns.",
    "indirect_tool": "Analyze the tool output for indirect prompt injection attacks.",
    "pipeline": "Monitor this pipeline stage for injection propagation.",
}


def load_dynamic_attacks(path: str) -> List[Dict[str, Any]]:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def load_task_data(task: str) -> List[Dict[str, Any]]:
    file_map = {"indirect_tool": "indirect.json"}
    fname = file_map.get(task, f"{task}.json")
    path = os.path.join(DATA_DIR, fname)
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def build_dataset(task: str, dynamic_attacks: List[Dict]) -> List[Dict[str, str]]:
    """Format examples as instruction-response pairs for SFT."""
    records = []
    instruction = TASK_INSTRUCTION.get(task, TASK_INSTRUCTION["easy"])

    # Static task data as positive/negative examples
    for sample in load_task_data(task):
        if task == "indirect_tool":
            user_text = (
                f"User asked: '{sample.get('user_query', '')}'\n"
                f"Tool: {sample.get('tool_name', '')}\n"
                f"Tool output:\n{sample.get('tool_output', '')}"
            )
        elif task == "pipeline":
            continue  # pipeline data is scenario-based, skip for now
        else:
            msg = sample.get("message") or ""
            context = sample.get("conversation")
            if context:
                user_text = "Conversation:\n" + "\n".join(context)
            else:
                user_text = f"Message:\n{msg}"

        correct_answer = json.dumps({
            "classification": sample["label"],
            "attack_type": sample.get("attack_type"),
            "explanation": f"This {'is' if sample['label'] == 'injection' else 'is not'} a prompt injection attack.",
            "severity": sample.get("severity"),
            "injection_vector": sample.get("injection_vector"),
        })

        records.append({
            "prompt": f"{SYSTEM_PROMPT}\n\n{instruction}\n\n{user_text}",
            "completion": correct_answer,
        })

    # Dynamic attacks (generated by /evolve) as hard negatives
    for attack in dynamic_attacks:
        msg = attack.get("message", "")
        records.append({
            "prompt": f"{SYSTEM_PROMPT}\n\n{instruction}\n\nMessage:\n{msg}",
            "completion": json.dumps({
                "classification": attack.get("true_classification", "injection"),
                "attack_type": attack.get("attack_type", "direct"),
                "explanation": "This message contains a prompt injection attack.",
                "severity": 0.7,
                "injection_vector": "user_message",
            }),
        })

    return records


def run_finetune(
    task: str,
    epochs: int,
    output_path: str,
    model_name: str = "meta-llama/Llama-3.2-1B-Instruct",
) -> None:
    try:
        import torch
        from datasets import Dataset
        from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
        from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
        from trl import SFTConfig, SFTTrainer
    except ImportError as e:
        print(f"[finetune] Missing dependency: {e}")
        print("[finetune] Install: pip install torch transformers peft trl bitsandbytes accelerate datasets")
        sys.exit(1)

    hf_token = os.environ.get("HF_TOKEN")
    dynamic = load_dynamic_attacks(os.path.join(DATA_DIR, "dynamic_attacks.json"))
    dataset_records = build_dataset(task, dynamic)

    if not dataset_records:
        print(f"[finetune] No training data found for task '{task}'")
        sys.exit(1)

    print(f"[finetune] Training on {len(dataset_records)} examples for task '{task}'")

    # Format as HuggingFace Dataset
    def format_example(ex: Dict) -> str:
        return f"<|user|>\n{ex['prompt']}\n<|assistant|>\n{ex['completion']}"

    texts = [format_example(r) for r in dataset_records]
    ds = Dataset.from_dict({"text": texts})

    # 4-bit quantization to fit on hackathon compute
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )

    print(f"[finetune] Loading model: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, token=hf_token)
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        token=hf_token,
    )
    model = prepare_model_for_kbit_training(model)

    lora_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    training_args = SFTConfig(
        output_dir="./finetune_output",
        num_train_epochs=epochs,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=10,
        save_steps=50,
        warmup_ratio=0.05,
        lr_scheduler_type="cosine",
        report_to="none",
        max_seq_length=512,
    )

    trainer = SFTTrainer(
        model=model,
        train_dataset=ds,
        args=training_args,
        tokenizer=tokenizer,
    )

    print("[finetune] Starting training...")
    trainer.train()

    # Save results stub
    os.makedirs(EVALS_DIR, exist_ok=True)
    results = {
        "task": task,
        "model": model_name,
        "training_examples": len(dataset_records),
        "dynamic_attacks_used": len(dynamic),
        "epochs": epochs,
        "note": "Run inference.py before and after to compute score delta",
    }
    with open(output_path, "w") as f:
        f.write("# Fine-tune Results\n\n")
        f.write(f"Model: `{model_name}`\n")
        f.write(f"Task: `{task}`\n")
        f.write(f"Training examples: {len(dataset_records)} ({len(dynamic)} from /evolve)\n")
        f.write(f"Epochs: {epochs}\n\n")
        f.write("## Score Delta\n\n")
        f.write("| Task | Before Fine-tune | After Fine-tune | Delta |\n")
        f.write("|------|-----------------|-----------------|-------|\n")
        f.write(f"| {task} | TBD | TBD | TBD |\n\n")
        f.write("Run `python inference.py` before and after to fill this table.\n")

    print(f"[finetune] Done. Results stub at {output_path}")
    print(f"[finetune] Run inference.py before/after to measure score delta")


def main() -> None:
    parser = argparse.ArgumentParser(description="LoRA fine-tune on prompt injection failure cases")
    parser.add_argument("--task", default="indirect_tool", choices=["easy", "medium", "hard", "indirect_tool"])
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--model", default="meta-llama/Llama-3.2-1B-Instruct")
    parser.add_argument("--output", default=os.path.join(EVALS_DIR, "finetune_results.md"))
    args = parser.parse_args()

    run_finetune(
        task=args.task,
        epochs=args.epochs,
        output_path=args.output,
        model_name=args.model,
    )


if __name__ == "__main__":
    main()
